### PR TITLE
Add Souffle.

### LINKED ISSUE #459: Include soufflé?
I've been finding [soufflé](https://souffle-lang.github.io/index.html) incredibly useful lately, and would like to incorporate it into some workflows (for Ubergraph and for GO). Would it be too specialized to include in the ODK docker image?

They have Ubuntu install instructions here: https://souffle-lang.github.io/install  Will that work for Apple M1?

### PR DESCRIPTION
**Pull request by balhoff**
Fixes #459.

This adds Souffle. I don't know if this will work on Apple M1.

### CODE REVIEW

**Comment by matentzn** [comment]
We will find out :)

**Comment by gouttegd** [comment]
Nope, Soufflé developpers don't provide a binary package for arm64. I'm trying to build it from source now, if it works I'll send a patch.

**Comment by balhoff** [comment]
Thanks for trying this @gouttegd!

**Comment by balhoff** [comment]
I asked the question at the Souffle repo: https://github.com/souffle-lang/souffle/discussions/2065

**Comment by gouttegd** [comment]
Closing as Soufflé is now installed as part of #475.

**Pull request closed without merging**
