### PR TITLE
Update TaxonRestriction.md

### PR DESCRIPTION
**Pull request by dosumis**
Updating + adding more practical suggestion for AP annotation.

### CODE REVIEW

**Comment by dosumis** [comment]
@shawntanzk - think I'm editing general docs in correct place.  Please let me know if not.  Also I seem to remember we had some general/theoretical doc on taxon restrictions.  Do you know where that might live?

**Comment by shawntanzk** [comment]
@dosumis literally facing the same problem atm - I can't seem to remember where the central location for documents that get distributed to all ODK ontologies reside. I don't think it's the docs here as they are different from the ones in ontology docs.

**Comment by matentzn** [comment]
Also note

https://github.com/OBOFoundry/obo-patterns.github.io

and in particular

http://obofoundry.org/obo-patterns.github.io/key-topics/taxon_constraints/

**Comment by shawntanzk** [comment]
I've moved this to https://github.com/OBOAcademy/obook/pull/96/files as part of ODK docs migration

**Pull request closed without merging**
