### PR TITLE
Add oaklib

### LINKED ISSUE #584: Add oaklib (libraries in path and runoak CLI) to ODK
This is a request to add OAK (ontology access kit) to the ODK.

https://github.com/INCATools/ontology-access-kit

Tagging @cmungall

### PR DESCRIPTION
**Pull request by gouttegd**
This PR adds the [Ontology Access Kit](https://github.com/INCATools/ontology-access-kit) to the `odkfull` image.

This brings in a whole new set of dependencies:

* [Obographviz](https://github.com/cmungall/obographviz), needed by the `runoak viz` command; 
* Node.js, needed to execute `obographviz` as it is a Javascript library and script;
* NPM, needed to install `obographviz` and its Javascript dependencies;
* Graphviz, which provides the `dot` command needed by `obographviz`.

closes #584

### CODE REVIEW

**Comment by matentzn** [comment]
This is very very amazing.. Thanks for doing this! Let's wait for @cmungall to review

**Review by cmungall — APPROVED** [review]

**Comment by cmungall** [comment]
I just moved ogv from my org to this org - does this affect the PR?

**Review by kltm — CHANGES_REQUESTED** [review]
I created a docker image in this branch as:
```
docker build .
```
and entered as
```
docker run --network host -it 079d3e44c526 /bin/bash
```
Inside the image, the lib `oaklib` and the `runoak` command do not seem exposed:
```
root@moiraine:/tools# runoak
bash: runoak: command not found
```
```ipython
In [1]: import oaklib
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-a904ee677e33> in <module>
----> 1 import oaklib

ModuleNotFoundError: No module named 'oaklib'
```
Is there something wrong with this test/invocation?

**Comment by gouttegd** [comment]
> I created a docker image in this branch as:
> 
> ```
> docker build .
> ```

That’s not how the ODK should be built. By trying to build it by calling `docker build` directly, you’re skipping the step of building the intermediate `odkbuild` image, which among other things assembles all the Python packages (including, in this branch, `oaklib`).

Build the ODK by running

```
make build
```

in the top-level directory.

**Review by kltm — APPROVED** [review]
@gouttegd Ah, cheers--I was looking in the main REAM, not the dev one. 
Retrying my testing, it all looks good to me now.

**Comment by gouttegd** [comment]
Thanks for the testing @kltm! Merging now, `oaklib` will be part of the next release.

**Pull request merged**
