### PR TITLE
Preparing ODK 1.2.29

### PR DESCRIPTION
**Pull request by matentzn**
- Option to remove owl:Nothing from release
- Adding linkml, kgx and funowl

Previously merged:
- [New base image](https://github.com/INCATools/ontology-development-kit/pull/434)
- [Remove unnecessary Makefile dependency](https://github.com/INCATools/ontology-development-kit/pull/432)
- [Fix bug with profile validation](https://github.com/INCATools/ontology-development-kit/pull/430)

### CODE REVIEW

**Comment by gouttegd** [comment]
FYI, the build failure above, which I can reproduce on my machine, seems to be prevented by replacing the calls to `pip3` by `python3 -m pip`:

```Dockerfile
&& python3 -m pip install --upgrade pip setuptools \
&& python3 -m pip install -r /tools/requirements.txt \
```

I don't know why it is so, but of note, `python(3) -m pip` is the preferred way of invoking pip; calling the `pip` executable directly is discouraged by pip developers (especially when upgrading pip itself).

**Comment by matentzn** [comment]
@gouttegd Do you want to make a PR to that end? a PR just into this one here 1.2.29 rather than master?

**Comment by matentzn** [comment]
@gouttegd I think I am getting close to ready to go here - if you want to give it a brief review, I will initiative the release process. I would also try to build the whole thing, including the multiarch image, given your instructions here:

https://github.com/INCATools/ontology-development-kit/blob/master/README-developers.md#docker

From what I see, I will run the following four commands:

```
make tests (to make sure all is well)
make publish (to publish the regular odkfull, like, dev images)
docker buildx create --name multiarch --driver docker-container --use (to set myself up for multiarch)
make publish-multiarch (to publish multiarch)
```

That sound ok to you?

**Comment by gouttegd** [comment]
Sounds good to me.

A few things to consider:
* If the only reason you pinned `upsetplot` to version 0.4.1 was to fix the build failure, then it's no longer needed now that we call pip with `python -m pip` – I tested again this morning, and I can confirm that the build passes even with the latest `upsetplot`, so you may consider un-pinning that package.
* I was planning to push this afternoon a PR for the changes to the test commands I mentioned in our chat yesterday. As I said, it's nothing urgent so it can easily wait for the next release, but it's up to you if you want to wait for that.
* Regarding the commands to build, note that `make publish-multiarch` will publish both the x86_64 image and the arm64 image, so you could dispense with the previous `make publish` step (the x86_64 image that you would publish at that step would soon after be overwritten by the one you'd publish at the `make publish-multiarch` step).
* Remember also that we have a GitHub Action to automatically publish the multi arch images upon release.

**Review by gouttegd — APPROVED** [review]

**Comment by matentzn** [comment]
Thanks a ton @gouttegd 

So can you write up the, from your perspective, correct workflow to create an ODK release that updates both obolibrary and obotools images? Everything including Github release etc?

**Comment by matentzn** [comment]
I am happy to wait for the testing, I am in no rush! As I said, end of next week is fine by me! You let me know!

**Comment by gouttegd** [comment]
> So can you write up the, from your perspective, correct workflow to create an ODK release that updates both obolibrary and obotools images? Everything including Github release etc?

Do you intend to keep the `obotools/` namespace? I thought you created it only as a temporary workaround to allow me to publish my arm64 image.

**Comment by gouttegd** [comment]
Right now neither the Makefile nor the GitHub Action are designed to publish the images under two namespaces, so for now publishing the images under `obotools/` would need to be done manually (we can easily change that later).

As for what would be the full process for a release, with the GitHub Action to automatically publish the multi-arch images it should be quite straightforward:

* Put the `master` branch in the state we want for release (i.e. merge any approved PR that we want included in that release, etc.).
* Do any amount of testing as needed to be confident we are ready for release (at the very least, do a local build with `make build` and run the test suite with `make tests`; possibly run some mock releases on known ontologies such as `FBbt`, etc.).
* Tag the release and push the tag to GitHub.
* From GitHub, create a formal release from the newly pushed tag. This should automatically trigger the `build-multiarch.yml` GitHub Action, leading to both the x86_64 and arm64 images being built and published under the `obolibrary/` namespace.

To then publish the multi-arch images under the `obotools/` namespace, one of us would then need to run locally:

```sh
$ docker buildx create --name multiarch --driver docker-container --use
$ make publish-multiarch IM=obotools/odkfull IMLITE=obotools/odklite DEV=obotools/odkdev
```

(The first command only being needed when you attempt a multi-arch build for the first time. Its effects are persistent, so it will never be needed again for any subsequent release — unless you completely reset your Docker installation in the meantime.)

**Comment by matentzn** [comment]
I love that, thank you! I will add it to the editors readme if you don't mind! Thats how we will do it!

**Comment by gouttegd** [comment]
> I love that, thank you! I will add it to the editors readme if you don't mind!

Be my guest. :)

**Pull request merged**
