### PR TITLE
864 better documentation for the project yaml parameters

### LINKED ISSUE #864: Add a human readable reference guide explaining the project YAML parameters
Spun out of a[ Slack discussion](https://obo-communitygroup.slack.com/archives/C01BKKED8R2/p1683707065645869?thread_ts=1683694703.704229&cid=C01BKKED8R2), we've identified the need to have a more practical overview of what project.YAML parameters are available and how to set them, based on https://github.com/INCATools/ontology-development-kit/blob/master/docs/project-schema.md.

### PR DESCRIPTION
**Pull request by StroemPhi**
closes #864

This PR adds links to the [project-schema.md](https://github.com/INCATools/ontology-development-kit/blob/master/docs/project-schema.md) in the ODK README as well as in the template ([_dynamic_files.jinja2](https://github.com/INCATools/ontology-development-kit/blob/master/template/_dynamic_files.jinja2)) that is used to builds customized docs.

### CODE REVIEW

**Review by anitacaron — APPROVED** [review]
Thanks for these improvements, Philip!

**Review by matentzn — APPROVED** [review]
Thanks!

**Comment by matentzn** [comment]
Conflicts?

**Comment by StroemPhi** [comment]
I had to merge the main branch into this PR branch, to get the changes made in #878. I don't know why it had a conflict with this one line. But it's now resolved.

**Comment by matentzn** [comment]
Thank you Phil, very appreciated

**Pull request merged**
