### PR TITLE
Add `fastobo-validator` to Dockerfile

### PR DESCRIPTION
**Pull request by althonos**
I added the latest stable `fastobo-validator` to the Dockerfile as discussed in #214 . Usage is as follow:
```make
x.obo: x.owl
  $(ROBOT) convert --check false -i $< -f obo -o $@.tmp.obo \ 
  && fastobo-validator $@.tmp.obo \
  && mv $@.tmp.obo $@; 
```

### CODE REVIEW

**Comment by althonos** [comment]
By the way, the final image could be made slimmer of about 100MB simply by removing `gcc` and other build dependencies after `pandas` is built :wink:

**Comment by matentzn** [comment]
This is all amazing! I will test it tomorrow. If you want to add some cleanup stuff that you think are not necessary (like removing gcc) feel free to do so any time! Thanks for the suggestion!

**Comment by matentzn** [comment]
I had to roll back the uninstall dependency command because unfortunately, it uninstalled some stuff that was needed elsewhere, in particular `make` for some reason... :P I will take it under advisement though and one day, when we launch another effort to shrink the image, we will try it again.

**Comment by althonos** [comment]
Maybe you can just uninstall `gcc` when you're done, its the largest build dependency and probably the one you don't really need :wink:

**Pull request merged**
