### PR TITLE
Add version info

### PR DESCRIPTION
**Pull request by matentzn**
This PR:
- makes VERSION a variable that is by OBO default the $(TODAY), but can be overwritten to be anything (like "2.3").
- adds owl:versionInfo to all release files
- moves version info definition into a single extensible variable (ANNOTATE_ONTOLOGY_VERSION)

#338

### CODE REVIEW

**Comment by matentzn** [comment]
Cheers Jim, thanks for letting me know.. Looking at this, owl:versionInfo does not seem to be mapped:

http://owlcollab.github.io/oboformat/doc/obo-syntax.html#5.8

Why it however gets forced into the obo namespace.. Strange! This problem replicates with ROBOT:

Starting from test_version_info.owl:

```
<owl:Ontology rdf:about="http://www.semanticweb.org/matentzn/ontologies/2020/5/untitled-ontology-1235">
        <owl:versionInfo rdf:datatype="http://www.w3.org/2001/XMLSchema#decimal">1.4</owl:versionInfo>
    </owl:Ontology>
```

Converting to obo (`robot convert -i test_version_info.owl -f obo -o test_version_info.obo`)

```
format-version: 1.2
ontology: http://www.semanticweb.org/matentzn/ontologies/2020/5/untitled-ontology-1235
property_value: owl:versionInfo "1.4" xsd:decimal
```

Then running:

```
robot convert -i test_version_info.obo -o test_version_info_from_obo.owl
```

test_version_info_from_obo.owl:
```
<owl:Ontology rdf:about="http://www.semanticweb.org/matentzn/ontologies/2020/5/untitled-ontology-1235">
        <obo:owl_versionInfo rdf:datatype="http://www.w3.org/2001/XMLSchema#decimal">1.4</obo:owl_versionInfo>
        <oboInOwl:hasOBOFormatVersion rdf:datatype="http://www.w3.org/2001/XMLSchema#string">1.2</oboInOwl:hasOBOFormatVersion>
    </owl:Ontology>
```

Then:
```
odk robot convert -i test_version_info_from_obo.owl -f obo -o test_version_info_from_obo_from_owl.obo
```

Resulting back in:

```
format-version: 1.2
ontology: http://www.semanticweb.org/matentzn/ontologies/2020/5/untitled-ontology-1235
property_value: owl:versionInfo "1.4" xsd:decimal
```

So it seems that the OBO serialiser/converter does not handle the owl namespace correctly! So this feature will only work for two cases:
1. OBO format is the end product
2. OWL is the edit format and there is no OBO intermediate

Very unfortunate!

**Comment by balhoff** [comment]
@matentzn I opened an issue: https://github.com/owlcs/owlapi/issues/947

**Comment by matentzn** [comment]
Thats great @balhoff thanks! Although it will take a few months for any such fix to go through ROBOT etc (especially if we are waiting for Protege).. I guess we will simply live with it? Or hold of on merging until this is sorted?

**Comment by balhoff** [comment]
I guess if the ODK workflow doesn't read OBO, it's not a big problem.

**Comment by matentzn** [comment]
The default workflow only writes obo, but of course the edit file could be OBO; I would say though that this is independent of this here issue, because this PR really just tags the final release artefact.

**Comment by cmungall** [comment]
Exactly - should not be a problem, no need to keep the versionInfo in the
edit file, and for release files it can be stamped

**Pull request merged**
