### PR TITLE
added java opts ENV to run.sh

### PR DESCRIPTION
**Pull request by matentzn**
This is so that the memory for dosdp can be controlled as well. I chose to use the same configuration for this as the robot_java_args - Its hard to envision a case where anyone would want to restrict the one but not the other..

### CODE REVIEW

**Comment by balhoff** [comment]
Would it be hard to change the setting to something more general like `project.java_memory_settings`?

**Comment by matentzn** [comment]
The problem is all those already existing odk yaml files! a change like this would not be downward compatible.. I see this solution lacks a bit of artistic grace, but since its unlikely most of our users would ever use dosdp entirely without robot, I think its good enough - and we can always separate it out again.. Do you think its a problem? Would you rather we added `java_memory_settings` and kept that separate from robot memory settings?

**Comment by balhoff** [comment]
That makes sense, I think it's fine to leave it how you have it.

**Comment by cmungall** [comment]
whatever you think best!

**Pull request merged**
