### PR TITLE
Fixing requirements in requirements.txt

### LINKED ISSUE #463: Consider freezing python versions in requirements.txt
This will allow us to a) circumvent the problems with the new resolved and b) create a more reproducible overall experience with the image.

See #461

### PR DESCRIPTION
**Pull request by matentzn**
Fixes #463

### CODE REVIEW

**Comment by matentzn** [comment]
As per slack discussion, @cthoyt recommends to pip freeze the full dependency chain, @gouttegd agrees, I am a bit.. against the effort involved in recreating the pip freeze every single time a change a dependency in the main requirements (which happens all the time). I am inclined to go against you both here :D

**Comment by gouttegd** [comment]
I don't know how you generated the last `requirements.txt`, but it's not good. There's still a conflict between `Click==8.0.1` and `kgx==1.5.2`, because the latter requires `Click~=7.0`.

**Comment by matentzn** [comment]
I ran it by running it without versions, then went into the container, then pip list.. Not sure how else to do it?

**Comment by gouttegd** [comment]
Well, apart from another rant about the ultimate crappiness that are automatic dependency resolvers, I don't know what to say, because there's even more problems: there's another conflict between `kgx==1.52` and `networkx==2.3` (`kgx-1.5.2` requires `networkx>=2.5`), and another issue with `rdflib-jsonld` (not sure I understand what's the problem with this one)…

**Comment by gouttegd** [comment]
In case anyone still doubts that the dependency resolver in pip is a piece of crap, consider the following:

* `kgx-1.5.4` *requires* `pystache>=0.0`
* I try to set a constraint `pystache==0.5.4`

And lo, `pip` complains that these two requirements are incompatible. WTF?

**Comment by gouttegd** [comment]
OK, I give up. `ontobio` requiring *precisely* `marshmallow==3.0.0b11` is the straw that breaks the camel's back.

**Comment by matentzn** [comment]
@gouttegd thank you so much for checking all that.. It makes me _really_ scared now that the set of python modules installed now in ODK is somehow mutually incompatible :D

**Comment by gouttegd** [comment]
Some of these incompatibilities clearly only exist in `pip`'s deranged resolver (e.g. in the example above, `pystache-0.5.4` is _not_ incompatible with `pystache>=0.5.4` as required by `kgx`).

But some are clearly real and are caused by some developers making an unreasonable (ab)use of pinning. `ontobio` in particular seems to be the worst offender, pinning against `networkx==2.3` (causing problems with `kgx`) and `marshmallow-3.0.0b11` (causing problems with `dataclasses`).

(Pinning dependencies in a package is already bad enough – and this whole issue could be a textbook example why –, but pinning against a *beta version* is insane.)

**Comment by matentzn** [comment]
I moved this back to draft now.. It left me shaken with fear that the set of libraries currently installed in ODK are mutually incompatible. I will need to come back to this before the 1.2.30 release.

**Comment by gouttegd** [comment]
I've submitted a PR to `ontobio` to remove the dependency to `marshmallow-3.0.0b11` (biolink/ontobio#587). Since they have already removed the pinning to `networkx==2.3`, if they accept it I don’t think there would be any conflict remaining.

**Comment by gouttegd** [comment]
`ontobio-2.7.10` has been released and no longer has any pinned dependencies. :confetti_ball:

There's still the problem with the "conflict" mentioned above between `kgx>=0.0` (as required by `kgx`) and `kgx==0.5.4` (as set by constraint). This is clearly bogus, but I can't pinpoint exactly the source of the problem.

Based on the error:

```
Collecting pystache==0.5.4
  Downloading pystache-0.5.4.tar.gz (75 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t7_qe_zl/pystac
he_eee31030b50c4fcea7d4bd80541fa6ae/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t7_qe_zl/pystache_eee31030b50c4fcea7d4bd80541f
a6ae/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from 
setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file
__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-36qsbsml
         cwd: /tmp/pip-install-t7_qe_zl/pystache_eee31030b50c4fcea7d4bd80541fa6ae/
    Complete output (3 lines):
    pystache: using: version '58.0.4' of <module 'setuptools' from '/usr/local/lib/python3.8/dist-packages/setuptools/__init__.p
y'>
    Warning: 'classifiers' should be a list, got type 'tuple'
    error in pystache setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d6/fd/eb8c212053addd941cc90baac307c00ac246ac3fce7166b86434c6eae963/p
ystache-0.5.4.tar.gz#sha256=f7bbc265fb957b4d6c7c042b336563179444ab313fb93a719759111eabd3b85a (from https://pypi.org/simple/pysta
che/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pystache==0.5.4 (from versions: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0
, 0.4.1, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4)
ERROR: No matching distribution found for pystache==0.5.4
```

I would venture that there's a bug somehwere in `pystache`'s `setup.py`, which prevents `pip` from even getting the version number correctly and therefore make the comparison with the constraint impossible.

But the main problem is that `pystache` looks like an abandoned project that has not seen any new development since 2014…

**Comment by cthoyt** [comment]
> `ontobio-2.7.10` has been released and no longer has any pinned dependencies. 🎊
> 
> There's still the problem with the "conflict" mentioned above between `pystache>=0.0` (as required by `kgx`) and `pystache==0.5.4` (as set by constraint). This is clearly bogus, but I can't pinpoint exactly the source of the problem.
> 
> Based on the error:
> 
> ```
> Collecting pystache==0.5.4
>   Downloading pystache-0.5.4.tar.gz (75 kB)
>     ERROR: Command errored out with exit status 1:
>      command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t7_qe_zl/pystac
> he_eee31030b50c4fcea7d4bd80541fa6ae/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t7_qe_zl/pystache_eee31030b50c4fcea7d4bd80541f
> a6ae/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from 
> setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file
> __, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-36qsbsml
>          cwd: /tmp/pip-install-t7_qe_zl/pystache_eee31030b50c4fcea7d4bd80541fa6ae/
>     Complete output (3 lines):
>     pystache: using: version '58.0.4' of <module 'setuptools' from '/usr/local/lib/python3.8/dist-packages/setuptools/__init__.p
> y'>
>     Warning: 'classifiers' should be a list, got type 'tuple'
>     error in pystache setup command: use_2to3 is invalid.
>     ----------------------------------------
> WARNING: Discarding https://files.pythonhosted.org/packages/d6/fd/eb8c212053addd941cc90baac307c00ac246ac3fce7166b86434c6eae963/p
> ystache-0.5.4.tar.gz#sha256=f7bbc265fb957b4d6c7c042b336563179444ab313fb93a719759111eabd3b85a (from https://pypi.org/simple/pysta
> che/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> ERROR: Could not find a version that satisfies the requirement pystache==0.5.4 (from versions: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0
> , 0.4.1, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4)
> ERROR: No matching distribution found for pystache==0.5.4
> ```
> 
> I would venture that there's a bug somehwere in `pystache`'s `setup.py`, which prevents `pip` from even getting the version number correctly and therefore makes the comparison with the constraint impossible.
> 
> But the main problem is that `pystache` looks like an abandoned project that has not seen any new development since 2014…

This is super wild. There are so many non-standard things going on in pystache - it looks like the developer recommends installing with a fork of setuptools. Best solution would be to switch away from using that to a more modern/maintained templating language like jinja2

**Comment by matentzn** [comment]
@gouttegd thanks for https://github.com/biolink/kgx/pull/337

**Comment by matentzn** [comment]
https://github.com/biolink/kgx/releases/tag/1.5.3

**Comment by gouttegd** [comment]
As far as I know, there's no more conflicts. :tada:

Now what I would suggest for how to manage the dependencies and the "versions freeze":

* Remove all version numbers from the `requirements.txt` file, _unless_ we happen to know that for a specific package we have some constraints (e.g. we know there's a bug in _foo-1.7.4_, or we know that we are not yet ready for the breaking changes introduced in _bar-3.0.0_).
* Create a `constraints.txt` file by installing all the required packages in a virtual environment, fixing any conflict that might arise (as of tonight there are none), and then running `pip freeze`.
* When building the ODK, provide `pip` with both the `requirements.txt` file and the `constraints.txt` file (`pip -r requirements.txt -c constraints.txt`).

The rationale for having two files of dependencies is that `requirements.txt` is the _manually managed_ list of _direct_ dependencies for the ODK, while `constraints.txt` is the _automatically generated_ list of _all_ dependencies (both direct and indirect).

Another way to see it is that `requirements.txt` is intended for ODK developers, whereas `constraints.txt` is to allow whoever wants to build the ODK on her machine (for any reason) to do so while being confident that (i) she will not run into any unexpected conflict and (ii) she will end up with exactly the same set of packages as we (the ODK developers) had when we built the ODK for the last public release.

Thoughts? If we agree on that I can push a commit with the appropriate changes.

**Comment by matentzn** [comment]
I am a bit overwhelmed this week but will take a look next week. @gouttegd super much appreciating your efforts here. Awesome.

**Comment by matentzn** [comment]
@gouttegd this plan sounds perfect. Would you be able to execute it, of shall I?

**Comment by gouttegd** [comment]
I can take care of it. ;)

**Comment by matentzn** [comment]
No longer needed.

**Pull request closed without merging**
