### PR TITLE
Install Soufflé using a multi-stage build

### PR DESCRIPTION
**Pull request by gouttegd**
This PR uses the problem of adding Soufflé to the ODK (#459) as an opportunity to test multi-stage builds (#466).

Soufflé is built on an intermediate image containing all its required build-time dependencies, and only the compiled program and its run-time dependencies are installed to the final ODK image. With all the build-time dependencies left out of the final image, the size increase due to the addition of Soufflé is minimal (~15 Mb).

@balhoff Can you build the ODK from this PR and test that Soufflé is working as you expect? Or provide some tests that I could use to check myself?

### CODE REVIEW

**Comment by balhoff** [comment]
Wow, thank you so much @gouttegd! I will give it a try.

**Comment by balhoff** [comment]
@gouttegd here is the result:

```
jim (master)$ docker run -m 12g  -v $PWD:/work -w /work --rm -ti obolibrary/odkfull souffle -c phenoscape-query.dl
terminate called after throwing an instance of 'std::runtime_error'
  what():  failed to locate mcpp pre-processor
```

**Comment by gouttegd** [comment]
Thanks @balhoff .

I'll push an update with the run-time dependencies suggested by Soufflé's Debian packager (I should have done that from the start…).

**Comment by balhoff** [comment]
@gouttegd any thoughts on this comment? https://github.com/souffle-lang/souffle/discussions/2065#discussioncomment-1330314

**Comment by gouttegd** [comment]
Closing as Soufflé is now installed as part of #475.

**Pull request closed without merging**
