### PR TITLE
Adding a preprocessing intermediate file to the ODK build process

### PR DESCRIPTION
**Pull request by matentzn**
This allows injecting custom preprocessing steps

### CODE REVIEW

**Comment by gouttegd** [comment]
Seems to be working file for FBbt’s `pre_release` custom pipeline (modulo some problems with some of our components, but that’s something that should be fixed in FBbt, not here).

**Review by gouttegd — APPROVED** [review]

**Comment by matentzn** [comment]
Risking it

**Comment by gouttegd** [comment]
@matentzn Merging this has broken the test suite, but this has nothing to do with the `EDIT_PREPROCESSED` feature. It’s because the PR somehow includes a new test file (`test-non-import-release.yaml`) that appears intended to test a feature from PR #643 (new release artefact `editors`).

I’d suggest removing that test file until the new feature is ready.

**Comment by matentzn** [comment]
Oh yeah, I dropped it from master and moved it where it belongs: https://github.com/INCATools/ontology-development-kit/pull/643/files

**Pull request merged**
