### PR TITLE
Removed files that are repeated in obook

### PR DESCRIPTION
**Pull request by shawntanzk**
CreateNewTerm - https://oboacademy.github.io/obook/howto/create-new-term/
DeleteAssertedSubClasses - https://oboacademy.github.io/obook/explanation/deleting-asserted-sub-classes/
MergedTerms - https://oboacademy.github.io/obook/howto/merge-terms/
ObsoleteTerm - https://oboacademy.github.io/obook/howto/obsolete-term/
TaxonRestriction - https://oboacademy.github.io/obook/howto/add-taxon-restrictions/
Synonyms - https://oboacademy.github.io/obook/reference/synonyms-obo/
TermComments - https://oboacademy.github.io/obook/explanation/term-comments/
NewSlim - https://oboacademy.github.io/obook/howto/add-new-slim/
NewSlimTerm - https://oboacademy.github.io/obook/howto/add-new-slim/
CreatingRepo - https://oboacademy.github.io/obook/howto/odk-create-repo/
DealingWithLargeOntologies - https://oboacademy.github.io/obook/howto/deal-with-large-ontologies/

I've left DailyWorkflow as it is broken up in bits in obook 
I think we should add a link to obook in the main readme or something so people know where to find documents, have not done this, will wait for docs call to discuss

### CODE REVIEW

**Comment by matentzn** [comment]
I know you will kill me shown, but I would prefer if the files stay, their content is deleted and replaced by a link to the corresponding obook page.. :P Sorry.

**Comment by shawntanzk** [comment]
lol I thought you might say that hence me putting the links in the comment so it would be easy to change to that :p I was wondering if it would be smarter to put it in the readme though? I think people coming in would mostly see the readme file

**Comment by matentzn** [comment]
I am worried users of this will be confused, that is why I think leave the individual pages:

https://ontology-development-kit.readthedocs.io/en/latest/

**Comment by shawntanzk** [comment]
Fair enough, will redo this to redirect each page accordingly then.

**Comment by matentzn** [comment]
Converted this to draft while not done, hope ok.

**Review by matentzn — APPROVED** [review]
Excellent man, thank you!

**Pull request merged**
