### PR TITLE
Add break lines to makefile

### LINKED ISSUE #553: Format the Makefile a bit nicer using line breaks \
From @gouttegd: 

> Cosmetic only: I’d like to generalise the use of line breaks (with \) to avoid overly long lines. We already do that for some rules, but not for all.

### PR DESCRIPTION
**Pull request by anitacaron**
Fixes #553

### CODE REVIEW

**Comment by matentzn** [comment]
Thank you! What line break rule did you apply? What is the maximum line break length now that is permitted?

**Comment by matentzn** [comment]
Also did you try building an example to see if you didn't remove too much whitespace?

**Comment by anitacaron** [comment]
> What line break rule did you apply? What is the maximum line break length now that is permitted? 

I put line breaks when the command line was more extensive than the general commands and when there was more than one command in the same line. I was looking into a real Makefile (UBERON).

> Also did you try building an example to see if you didn't remove too much whitespace?

Looking better in the result, I'll fix some whitespaces.

**Comment by matentzn** [comment]
Try this on PATO and CL - there are a lot of empty lines generated in the resulting `Makefile`!

**Review by matentzn — APPROVED** [review]
I think its fine, but I wanted a brief look of @gouttegd when he is back just in case.

**Comment by matentzn** [comment]
I will risk it.

**Pull request merged**
