### PR TITLE
Fix bug that docs workflow is created during seeding

### PR DESCRIPTION
**Pull request by matentzn**

### CODE REVIEW

**Comment by matentzn** [comment]
@anitacaron did you mean to approve this?

**Comment by anitacaron** [comment]
The problem is the `docs` GitHub action that is created [as default](https://github.com/INCATools/ontology-development-kit/blob/master/template/_dynamic_files.jinja2#L1769) and the `mkdocs.yml` file is created with `documentation` option.

**Review by anitacaron — CHANGES_REQUESTED** [review]
Need to change the code in line 1769 or change the default value.

```
{% if (('github_actions' in project.ci) and ('docs' in project.workflows)) %}
```

**Comment by anitacaron** [comment]
I can update the PR with your decision.

**Comment by anitacaron** [comment]
The default workflow should be 'qc' instead of 'docs'.

**Comment by anitacaron** [comment]
Or no default at all.

**Comment by matentzn** [comment]
Ok, I will let you decide how to move this forward :) Thank you!

**Review by anitacaron — APPROVED** [review]

**Pull request merged**
