### PR TITLE
Add Ammonite to Dockerfile

### PR DESCRIPTION
**Pull request by matentzn**
@balhoff 

Added old PR to correct file here for you, in case you want to fix it!

### CODE REVIEW

**Comment by balhoff** [comment]
@matentzn thanks! I think this is good to go now.

**Comment by matentzn** [comment]
Cool will be merged with the next ODK version. Is there some urgency?

**Comment by balhoff** [comment]
Not super urgent. Would be nice to use in the near future.

**Comment by matentzn** [comment]
Closing in favour of https://github.com/INCATools/ontology-development-kit/pull/307 (after major Dockerfile reshuffle). I manually added Ammonite there.

**Pull request closed without merging**
