### PR TITLE
Update MergeTerms.md

### PR DESCRIPTION
**Pull request by shawntanzk**
Changed merge documentation to deprecate term
@dosumis @matentzn happy for you guys to change anything

### CODE REVIEW

**Comment by matentzn** [comment]
Is this aligned with the [mondo docs](https://mondo.readthedocs.io/en/latest/editors-guide/merging-and-obsoleting/)?

**Comment by shawntanzk** [comment]
> Is this aligned with the [mondo docs](https://mondo.readthedocs.io/en/latest/editors-guide/merging-and-obsoleting/)?

no, unfortunately it is not - happy to look more into this and figure it out as at quick glance I do it in a similar way that is manual which is not recommended

**Comment by matentzn** [comment]
We need @nicolevasilevsky to review this, and after that @dosumis 

@nicolevasilevsky would you be able to review? Feel free to fix PR yourself, no need to comment. Just use GitHUbs edit feature.

**Comment by nicolevasilevsky** [comment]
@matentzn, @dosumis, @shawntanzk  can I get edit rights to this repo?

**Comment by nicolevasilevsky** [comment]
Yes, this is different than how we merge terms in Mondo. I use an owl tools command to merge in Mondo. Should I add this to this ODK documentation?

**Comment by matentzn** [comment]
I gave you access now, thank you @nicolevasilevsky

**Comment by matentzn** [comment]
@shawntanzk @nicolevasilevsky @gouttegd and I are preparing a new ODK release soon, and it would be good if we could finish this - key items remain to be done is:

1. Ensure the workflows between Mondo and this ones are aligned (make a comment here in the pull request comments for any differences).
2. Add any related commands like owltools mass obsoletion etc.

**Comment by nicolevasilevsky** [comment]
@matentzn I am working on this now

**Comment by nicolevasilevsky** [comment]
I had to create a fork, see PR:
https://github.com/INCATools/ontology-development-kit/pull/479

I added a section on merging using owltools

**Review by matentzn — APPROVED** [review]
I would have liked someone to look over this, but lets merge it and iterate over it.

**Pull request merged**
