### PR TITLE
annotate base with module type resource rather than string

### PR DESCRIPTION
**Pull request by matentzn**
Make sure the base module annotation is to a resource, not to a string.

### CODE REVIEW

**Comment by matentzn** [comment]
Check here: http://robot.obolibrary.org/annotate

**Comment by wdduncan** [comment]
The checks failed:
```
The command '/bin/sh -c wget http://build.berkeleybop.org/userContent/owltools/owltools -O /tools/owltools &&     wget http://build.berkeleybop.org/userContent/owltools/ontology-release-runner -O /tools/ontology-release-runner &&     wget http://build.berkeleybop.org/userContent/owltools/owltools-oort-all.jar -O /tools/owltools-oort-all.jar &&     chmod +x /tools/owltools &&     chmod +x /tools/ontology-release-runner &&     chmod +x /tools/owltools-oort-all.jar' returned a non-zero code: 8
Makefile:49: recipe for target 'docker-build-use-cache' failed
make: *** [docker-build-use-cache] Error 8
The command "make docker-test" exited with 2.
```
But it says the branch has no conficts.

**Comment by matentzn** [comment]
Yeah, right now none of our test pipelines work because of:
https://github.com/INCATools/ontology-development-kit/issues/332

I will make sure the tests pass before I merge this - when the ticket above is solved.

**Comment by wdduncan** [comment]
I'm also curious about the workflow. Are you using the Makefile.jinja2 to create the Makefile?

**Comment by matentzn** [comment]
Yeah, so the jinja templates are instantiated whenever someone runs the ODK repo creator! So when someone calls odk.py, Jinja is run, and Makefile.jinja gets compiled into Makefile with all the Jinja variables resolved..

**Comment by wdduncan** [comment]
So ... is the branch safe to merge even thought the check failed? I don't know much about Jenkins or Travis.

**Comment by matentzn** [comment]
If you are ok with the fix, just click on `files changed` --> `review` --> `Approve` and I will take care of the rest. Thanks!

**Comment by wdduncan** [comment]
No problem ... the changes look fine to me.

**Pull request merged**
