### PR TITLE
Update constraints.txt

### PR DESCRIPTION
**Pull request by gouttegd**
This pull request updates constraints.txt. Make sure you run make tests manually.

### CODE REVIEW

**Comment by gouttegd** [comment]
@matentzn Not sure why the action was triggered now (I didn’t change the cron setting, the workflow is still supposed to be run at 1pm every Monday)… But at least we can see that it seems to be working.

The fact that the PR seems to be coming from me is the expected consequence of using a dedicated token instead of `GITHUB_TOKEN`: I created the dedicated token, so everything it does appear to come from me.

What puzzles me is the fact that the _commit_ seems to be coming from you. I don’t know why that is the case.

**Comment by matentzn** [comment]
i triggered it!

**Comment by gouttegd** [comment]
Ah, OK! This also explains why you are the committer, instead of the `github-actions` bot. All fine then.

**Comment by gouttegd** [comment]
Was it really necessary to merge that PR just to get the latest version of `openai`? I thought you just wanted to check that everything was working.

Now I have to update #1129 because `pip-constraints` has changed while the test suite was running.

**Comment by matentzn** [comment]
Sorry man, no it was not necessary; I thought of your PR too late. My apologies, keeping my hands off it now.

**Pull request merged**
