### PR TITLE
Update Readme to point to ODK paper

### PR DESCRIPTION
**Pull request by shawntanzk**

### CODE REVIEW

**Review by gouttegd — APPROVED** [review]
No objection, obviously, but we should also update the `CITATION.cff` file.

**Comment by gouttegd** [comment]
(P.S. Ignore the ”failed” CI check. I manually cancelled it – no point in wasting several hours of computing power for a PR that does not change any single line of code.)

**Comment by shawntanzk** [comment]
ah didn't even know that file existed, will make the change to that file on Monday or smth on this branch

**Comment by gouttegd** [comment]
Done (had nothing better to do for a few minutes :D ).

**Comment by shawntanzk** [comment]
sweet! thanks man :)

**Pull request merged**
