### PR TITLE
WIP: relation-graph #403

### PR DESCRIPTION
**Pull request by cmungall**
@balhoff is the path I am on correct? Should we try and inject UG configs into ODK, or have UG be something that sits above?

### CODE REVIEW

**Comment by matentzn** [comment]
If you get this to work that would be amazing

**Comment by cmungall** [comment]
@balhoff @matentzn should we try and build RG with sbt as part of the Dockerfile, or would it make more sense to build the executables as part of RG releases?

**Comment by balhoff** [comment]
I publish a pre-built executable at the RG repo: https://github.com/balhoff/relation-graph/releases/tag/v1.1

**Comment by matentzn** [comment]
Isnt sbt already fully in ODK? we could install it there, I don't think this is a problem!

**Comment by matentzn** [comment]
Obviously pre-built should be included no matter what.

**Comment by matentzn** [comment]
Superceded by #529

**Pull request closed without merging**
